// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonContent: typeof import('./src/layouts/CommonContent.vue')['default']
    CommonFooter: typeof import('./src/layouts/CommonFooter.vue')['default']
    CommonHeader: typeof import('./src/layouts/CommonHeader.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
