// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/layouts/CommonHeader.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    ICarbonUserAvatarFilled: typeof import('~icons/carbon/user-avatar-filled')['default']
    IIconoirLanguage: typeof import('~icons/iconoir/language')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
